{% set python_min = '3.10.0' %}
{% set name = "pylabeladjust" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylabeladjust-{{ version }}.tar.gz
  sha256: 23c1f9f8096c5c7de9fa79678ce729ca3730b88d979997fa24e99c037a48f59b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pyqtree >=1.0.0,<2.0.0
    - tqdm >=4.66.2,<5.0.0
    - pandas >=2.0.3,<3.0.0
    - matplotlib-base >=3.7.1,<4.0.0

test:
  imports:
    - pylabeladjust
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MNoichl/pylabeladjust
  summary: "`pylabeladjust` is a port of Gephi's Label-Adjust algorithm to python."
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lmcinnes
